### ISSUE TITLE
unable to open supervise/ok: file does not exist

### ISSUE THREAD

**Issue by ravener** [termux/termux-services#17] opened 2021-08-28 05:12 UTC
I keep getting this when I try to enable ftp

```
~  sv-enable ftpd
warning: ftpd: unable to open supervise/ok: file does not exist
 ✘  ~  sv up ftpd
warning: ftpd: unable to open supervise/ok: file does not exist
 ✘  ~ 
```

Some `termux-info`
```
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Fri Apr 19 13:20:06 CST 2019 armv8l Android
Device manufacturer:
HUAWEI
Device model:
AMN-LX9
```

**Comment by Grimler91** [comment] 2021-08-28 05:38
Duplicate of https://github.com/termux/termux-services/issues/10. Check if killing the runsv process helps, as per https://github.com/termux/termux-services/issues/10#issuecomment-907380971

**Closed by Grimler91** 2021-08-28 05:38 UTC

**Comment by ravener** [comment] 2021-08-28 14:00
@Grimler91 trying to source the file manually gives me this error: 
```
~  source $PREFIX/etc/profile.d/start-services.sh
/data/data/com.termux/files/usr/etc/profile.d/start-services.sh (line 3): Command substitutions not allowed
(service-daemon start >/dev/null 2>&1 & )
^
from sourcing file /data/data/com.termux/files/usr/etc/profile.d/start-services.sh
source: Error while reading file '/data/data/com.termux/files/usr/etc/profile.d/start-services.sh'
 ✘  ~ 
```
I'm using fish shell btw.

**Comment by Grimler91** [comment] 2021-08-28 14:09
For fish shell you should source start-services.fish, but you will need to kill all the running runsv processes first before you can start it again anyways. 

Just killing `runsv ftpd` should be enough (rather than sourcing the start script). Check for the PID of the `runsv ftpd` process with `ps aux`, kill the process, and wait and see if ftpd start correctly and `sv status ftpd` reports OK

**Comment by ravener** [comment] 2021-08-28 14:21
Actually it's not even running. But the script runs, the env vars are applied but it breaks on the `service-daemon`
```
~  service-daemon start
Starting daemon: service-daemon/data/data/com.termux/files/usr/bin/service-daemon: 6: /data/data/com.termux/files/usr/bin/service-daemon: start-stop-daemon: not found
 ✘  ~ 
```
am I missing a package?

**Comment by Grimler91** [comment] 2021-08-28 14:30
> start-stop-daemon: not found

seems weird, start-stop-daemon belongs to dpkg, which cannot be uninstalled. Do you have start-stop-daemon in $PREFIX/bin? And can you run it?

**Comment by Grimler91** [comment] 2021-08-28 14:34
We should clearly do something about how service-daemon is started anyways, redirecting stderr to /dev/null is a bad idea when an issue appear

**Comment by ravener** [comment] 2021-08-28 14:38
Thanks for pointing out the package, I just don't update my stuff often. Updating dpkg fixed it, all good now.
